
type OrderCardProps = {
  orderNumber: string;
    totalAmount: number;
      itemCount: number;
        status: "Pending" | "Preparing" | "Ready for Pickup" | "Completed";
          date: string;
            onView?: () => void;
            };

            const statusColors = {
              Pending: "#F59E0B",
                Preparing: "#3B82F6",
                  "Ready for Pickup": "#10B981",
                    Completed: "#6B7280",
                    };

                    export default function OrderCard({
                      orderNumber,
                        totalAmount,
                          itemCount,
                            status,
                              date,
                                onView,
                                }: OrderCardProps) {
                                  return (
                                      <div
                                            style={{
                                                    background: "#fff",
                                                            borderRadius: "16px",
                                                                    padding: "16px",
                                                                            marginBottom: "16px",
                                                                                    border: "1px solid #E5E7EB",
                                                                                            boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
                                                                                                  }}
                                                                                                      >
                                                                                                            <div
                                                                                                                    style={{
                                                                                                                              display: "flex",
                                                                                                                                        justifyContent: "space-between",
                                                                                                                                                  alignItems: "center",
                                                                                                                                                            marginBottom: "12px",
                                                                                                                                                                    }}
                                                                                                                                                                          >
                                                                                                                                                                                  <strong
                                                                                                                                                                                            style={{
                                                                                                                                                                                                        color: "#1565C0",
                                                                                                                                                                                                                    fontSize: "17px",
                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                #{orderNumber}
                                                                                                                                                                                                                                                        </strong>

                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                      backgroundColor: statusColors[status],
                                                                                                                                                                                                                                                                                                  color: "#fff",
                                                                                                                                                                                                                                                                                                              padding: "5px 10px",
                                                                                                                                                                                                                                                                                                                          borderRadius: "20px",
                                                                                                                                                                                                                                                                                                                                      fontSize: "12px",
                                                                                                                                                                                                                                                                                                                                                  fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                              {status}
                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                    margin: "6px 0",
                                                                                                                                                                                                                                                                                                                                                                                                                              color: "#555",
                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                    🛒 Items: <strong>{itemCount}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  margin: "6px 0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "#555",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  💰 Total: <strong>₦{totalAmount.toLocaleString()}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin: "6px 0 15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#777",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                📅 {date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onView}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#1565C0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            View Order
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }