import {useState} from "react";
import Header from "../../components/Header";
import SearchBar from "../../components/SearchBar";
import CategoryCard from "../../components/CategoryCard";
import ProductCard from "../../components/ProductCard";
import BottomNavigation from "../../components/BottomNavigation";

export default function Home() {
   const [search, setSearch] = useState("");

     const categories = [
         {
               name: "Beverages",
                     image: "https://via.placeholder.com/80",
                         },
                             {
                                   name: "Groceries",
                                         image: "https://via.placeholder.com/80",
                                             },
                                                 {
                                                       name: "Snacks",
                                                             image: "https://via.placeholder.com/80",
                                                                 },
                                                                     {
                                                                           name: "Household",
                                                                                 image: "https://via.placeholder.com/80",
                                                                                     },
                                                                                       ];

                                                                                         const products = [
                                                                                             {
                                                                                                   id: "1",
                                                                                                         name: "Peak Milk",
                                                                                                               image: "https://via.placeholder.com/300",
                                                                                                                     price: 1800,
                                                                                                                           stock: 15,
                                                                                                                               },
                                                                                                                                   {
                                                                                                                                         id: "2",
                                                                                                                                               name: "Golden Morn",
                                                                                                                                                     image: "https://via.placeholder.com/300",
                                                                                                                                                           price: 2500,
                                                                                                                                                                 stock: 10,
                                                                                                                                                                     },
                                                                                                                                                                         {
                                                                                                                                                                               id: "3",
                                                                                                                                                                                     name: "Indomie Noodles",
                                                                                                                                                                                           image: "https://via.placeholder.com/300",
                                                                                                                                                                                                 price: 450,
                                                                                                                                                                                                       stock: 40,
                                                                                                                                                                                                           },
                                                                                                                                                                                                               {
                                                                                                                                                                                                                     id: "4",
                                                                                                                                                                                                                           name: "Coca-Cola",
                                                                                                                                                                                                                                 image: "https://via.placeholder.com/300",
                                                                                                                                                                                                                                       price: 600,
                                                                                                                                                                                                                                             stock: 30,
                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                   ];

                                                                                                                                                                                                                                                     return (
                                                                                                                                                                                                                                                         <>
                                                                                                                                                                                                                                                             <Header title="Expresspick" />
                                                                                                                                                                                                                                                               <Header userName="Customer" />

                                                                                                                                                                                                                                                                     <div
                                                                                                                                                                                                                                                                             style={{
                                                                                                                                                                                                                                                                                       padding: "20px",
                                                                                                                                                                                                                                                                                                 paddingBottom: "100px",
                                                                                                                                                                                                                                                                                                         }}
                                                                                                                                                                                                                                                                                                               >
                                                                                                                                                                                                                                                                                                                       <SearchBar
                                                                                                                                                                                                                                                                                                                                 value={search}
                                                                                                                                                                                                                                                                                                                                           onChange={(e) => setSearch(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                   />

                                                                                                                                                                                                                                                                                                                                                           <h2>Categories</h2>

                                                                                                                                                                                                                                                                                                                                                                   <div
                                                                                                                                                                                                                                                                                                                                                                             style={{
                                                                                                                                                                                                                                                                                                                                                                                         display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                     gap: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                 overflowX: "auto",
                                                                                                                                                                                                                                                                                                                                                                                                                             marginBottom: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                       }}
                                                                                                                                                                                                                                                                                                                                                                                                                                               >
                                                                                                                                                                                                                                                                                                                                                                                                                                                         {categories.map((category) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <CategoryCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   key={category.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 name={category.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               image={category.image}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <h2>Featured Products</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               gridTemplateColumns: "repeat(auto-fill,minmax(180px,1fr))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           gap: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {products.map((product) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <ProductCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 key={product.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               name={product.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             image={product.image}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           price={product.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         stock={product.stock}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onAddToCart={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       alert(`${product.name} added to cart`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <BottomNavigation />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
