import { useState } from "react";
import Header from "../../components/Header";
import Button from "../../components/Button";
import BottomNavigation from "../../components/BottomNavigation";

export default function ProductDetails() {
  const [quantity, setQuantity] = useState(1);

    const product = {
        name: "Peak Milk",
            image: "https://via.placeholder.com/400",
                price: 1800,
                    stock: 25,
                        description:
                              "Peak Milk is a nutritious powdered milk suitable for the whole family.",
                                };

                                  return (
                                      <>
                                            <Header userName="Customer" />

                                                  <div
                                                          style={{
                                                                    padding: "20px",
                                                                              paddingBottom: "100px",
                                                                                      }}
                                                                                            >
                                                                                                    <img
                                                                                                              src={product.image}
                                                                                                                        alt={product.name}
                                                                                                                                  style={{
                                                                                                                                              width: "100%",
                                                                                                                                                          borderRadius: "16px",
                                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                                }}
                                                                                                                                                                                        />

                                                                                                                                                                                                <h2>{product.name}</h2>

                                                                                                                                                                                                        <h3
                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                              color: "#1565C0",
                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                          ₦{product.price.toLocaleString()}
                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                    <strong>Available:</strong> {product.stock} units
                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                    <p
                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                          lineHeight: 1.7,
                                                                                                                                                                                                                                                                                                                                      color: "#555",
                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                  {product.description}
                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                        display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                gap: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            margin: "25px 0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  quantity > 1 && setQuantity(quantity - 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>{quantity}</strong>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setQuantity(quantity + 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button fullWidth>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Add to Cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <BottomNavigation />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

